# FRONT STEERING GROUP CONTROLLER
front_steering_controller:
  type: "position_controllers/JointGroupPositionController"
  joints:
    - left_front_steering_joint
    - right_front_steering_joint

# REAR DRIVE GROUP CONTROLLER
rear_drive_controller:
  type: "velocity_controllers/JointGroupVelocityController"
  joints:
    - left_rear_wheel_joint
    - right_rear_wheel_joint


gazebo_ros_control:
  pid_gains:
    left_front_steering_joint:
      p: 10.0
      i: 0.01
      d: 0.1
    right_front_steering_joint:
      p: 10.0
      i: 0.01
      d: 0.1
    left_rear_wheel_joint:
      p: 1.0
      i: 0.0
      d: 0.0
    right_rear_wheel_joint:
      p: 1.0
      i: 0.0
      d: 0.0

